// This file is auto-generated by @hey-api/openapi-ts

export const UnityReleaseDigitalValueSchema = {
    description: 'A Unity Release Digital Value as defined on Release Live Platform.',
    type: 'object',
    properties: {
        value: {
            type: 'number',
            description: 'The value of the Unity Release Digital Value.',
            example: 1524000000
        },
        unit: {
            type: 'string',
            enum: ['BYTE', 'KILOBYTE', 'MEGABYTE', 'GIGABYTE'],
            description: 'The unit of the Unity Release Digital Value.',
            nullable: false,
            example: 'BYTE'
        }
    },
    required: ['value', 'unit']
} as const;

export const UnityReleaseNotesSchema = {
    description: 'A Unity Release Notes File as defined on Release Live Platform.',
    type: 'object',
    properties: {
        url: {
            type: 'string',
            description: 'The URL of the Unity Release notes.',
            example: 'https://storage.googleapis.com/live-platform-resources-prd/templates/assets/2020_3_44f1_750922b691/2020_3_44f1_750922b691.md'
        },
        integrity: {
            type: 'string',
            description: 'The Subresource Integrity of the Unity Release notes as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.',
            example: 'sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo='
        },
        type: {
            type: 'string',
            enum: ['TEXT', 'TAR_GZ', 'TAR_XZ', 'ZIP', 'PKG', 'EXE', 'PO', 'DMG', 'LZMA', 'LZ4', 'MD', 'PDF'],
            description: 'The file type of the Unity Release notes.',
            nullable: false,
            example: 'MD'
        }
    },
    required: ['url', 'type']
} as const;

export const UnityReleaseThirdPartyNoticeSchema = {
    description: 'A Unity Release Third Party Notice File as defined on Release Live Platform.',
    type: 'object',
    properties: {
        originalFileName: {
            type: 'string',
            description: 'The original file name of the Unity Release Third Party Notice.',
            example: '2020.3.26f1-WinPlayerNoDevelopment-release.pdf'
        },
        url: {
            type: 'string',
            description: 'The URL of the Unity Release Third Party Notice.',
            example: 'https://storage.googleapis.com/live-platform-resources-prd/templates/assets/2020_3_26f1_Win_Player_No_Development_release_ff4b1c5e4a/2020_3_26f1_Win_Player_No_Development_release_ff4b1c5e4a.pdf'
        },
        integrity: {
            type: 'string',
            description: 'The Subresource Integrity of the Unity Release Third Party Notice as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.',
            example: 'sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo='
        },
        type: {
            type: 'string',
            enum: ['TEXT', 'TAR_GZ', 'TAR_XZ', 'ZIP', 'PKG', 'EXE', 'PO', 'DMG', 'LZMA', 'LZ4', 'MD', 'PDF'],
            description: 'The file type of the Unity Release Third Party Notice.',
            nullable: false,
            example: 'PDF'
        }
    },
    required: ['originalFileName', 'url', 'type']
} as const;

export const UnityReleaseModuleEulaSchema = {
    description: 'A Unity Release module end-user license agreement.',
    type: 'object',
    properties: {
        url: {
            type: 'string',
            description: 'The URL of the Unity Release module end-user license agreement.',
            example: 'https://go.microsoft.com/fwlink/?linkid=2092535'
        },
        integrity: {
            type: 'string',
            description: 'The Subresource Integrity of the Unity Release module end-user license agreement as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.',
            example: 'sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo='
        },
        type: {
            type: 'string',
            enum: ['TEXT', 'TAR_GZ', 'TAR_XZ', 'ZIP', 'PKG', 'EXE', 'PO', 'DMG', 'LZMA', 'LZ4', 'MD', 'PDF'],
            description: 'The file type of the Unity Release module end-user license agreement.',
            nullable: false,
            example: 'TEXT'
        },
        label: {
            type: 'string',
            description: 'The label of the Unity Release module end-user license agreement.',
            example: 'Visual Studio for Mac License Terms'
        },
        message: {
            type: 'string',
            description: 'The message of the Unity Release module end-user license agreement.',
            example: 'Please review and accept the license terms before downloading and installing Visual Studio for Mac and Mono.'
        }
    },
    required: ['url', 'type', 'label', 'message']
} as const;

export const UnityReleaseModuleExtractedPathRenameSchema = {
    description: 'A Unity Release Module Extracted Path Rename.',
    type: 'object',
    properties: {
        from: {
            type: 'string',
            description: 'The location of the module when extracted.',
            example: '{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/android-ndk-r19'
        },
        to: {
            type: 'string',
            description: 'The location the module must be moved to.',
            example: '{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/NDK'
        }
    },
    required: ['from', 'to']
} as const;

export const UnityReleaseModuleSchema = {
    description: 'A Unity Release module.',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'The ID of the Unity Release module.',
            example: 'android-ndk-r19'
        },
        slug: {
            type: 'string',
            description: 'The slug of the Unity Release module. This is unique across all Unity Release Modules.',
            example: '2020.3.44f1-windows-x86_64-android-ndk-r19'
        },
        name: {
            type: 'string',
            description: 'The name of the Unity Release module.',
            example: 'Android NDK'
        },
        description: {
            type: 'string',
            description: 'The description of the Unity Release module.',
            example: 'Android NDK r19'
        },
        category: {
            type: 'string',
            enum: ['DOCUMENTATION', 'PLATFORM', 'LANGUAGE_PACK', 'DEV_TOOL', 'PLUGIN', 'COMPONENT'],
            description: 'The category of the Unity Release module.',
            nullable: false,
            example: 'PLATFORM'
        },
        url: {
            type: 'string',
            description: 'The URL of the Unity Release module.',
            example: 'https://dl.google.com/android/repository/android-ndk-r19-windows-x86_64.zip'
        },
        integrity: {
            type: 'string',
            description: 'The Subresource Integrity of the Unity Release module as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.',
            example: 'sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo='
        },
        type: {
            type: 'string',
            enum: ['TEXT', 'TAR_GZ', 'TAR_XZ', 'ZIP', 'PKG', 'EXE', 'PO', 'DMG', 'LZMA', 'LZ4', 'MD', 'PDF'],
            description: 'The file type of the Unity Release module.',
            nullable: false,
            example: 'ZIP'
        },
        downloadSize: {
            '$ref': '#/components/schemas/UnityReleaseDigitalValue',
            description: 'The download size of the Unity Release module.'
        },
        installedSize: {
            '$ref': '#/components/schemas/UnityReleaseDigitalValue',
            description: 'The installed size of the Unity Release module.'
        },
        subModules: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityReleaseModule'
            },
            nullable: true,
            description: 'The optional sub-modules of the Unity Release module. The parent must be downloaded to download a sub-module.',
            example: []
        },
        required: {
            type: 'boolean',
            description: 'The indicator for whether the Unity Release module needs to be downloaded if the parent is downloaded.',
            example: true
        },
        hidden: {
            type: 'boolean',
            description: 'The indicator for whether the Unity Release module needs to be hidden when displaying modules in a UI.',
            example: true
        },
        extractedPathRename: {
            '$ref': '#/components/schemas/UnityReleaseModuleExtractedPathRename',
            description: 'The location to move a Unity Release Module when extracted or unzipped.'
        },
        preSelected: {
            type: 'boolean',
            description: 'The indicator for whether the Unity Release module should be pre-selected.',
            example: false
        },
        destination: {
            type: 'string',
            description: 'The file destination of the Unity Release module.',
            example: '{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/NDK'
        },
        eula: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityReleaseModuleEula'
            },
            nullable: true,
            description: 'The end-user license agreements of the Unity Release module.',
            example: []
        }
    },
    required: ['id', 'slug', 'name', 'description', 'category', 'url', 'type', 'downloadSize', 'installedSize', 'required', 'hidden', 'preSelected']
} as const;

export const UnityReleaseDownloadSchema = {
    description: 'A Unity Release Hub download.',
    type: 'object',
    properties: {
        url: {
            type: 'string',
            description: 'The URL of the Unity Release Hub download.',
            example: 'https://download.unity3d.com/download_unity/7f159b6136da/Windows64EditorInstaller/UnitySetup64-2020.3.44f1.exe'
        },
        integrity: {
            type: 'string',
            description: 'The Subresource Integrity of the Unity Release Hub download as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.',
            example: 'sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo='
        },
        type: {
            type: 'string',
            enum: ['TEXT', 'TAR_GZ', 'TAR_XZ', 'ZIP', 'PKG', 'EXE', 'PO', 'DMG', 'LZMA', 'LZ4', 'MD', 'PDF'],
            description: 'The file type of the Unity Release Hub download.',
            nullable: false,
            example: 'EXE'
        },
        platform: {
            type: 'string',
            enum: ['MAC_OS', 'LINUX', 'WINDOWS'],
            description: 'The platform of the Unity Release Hub download.',
            nullable: false,
            example: 'WINDOWS'
        },
        architecture: {
            type: 'string',
            enum: ['X86_64', 'ARM64'],
            description: 'The architecture of the Unity Release Hub download.',
            nullable: false,
            example: 'X86_64'
        },
        downloadSize: {
            '$ref': '#/components/schemas/UnityReleaseDigitalValue',
            description: 'The download size of the Unity Release Hub download.'
        },
        installedSize: {
            '$ref': '#/components/schemas/UnityReleaseDigitalValue',
            description: 'The installed size of the Unity Release Hub download.'
        },
        modules: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityReleaseModule'
            },
            nullable: false,
            description: 'The modules of the Unity Release Hub download.'
        }
    },
    required: ['url', 'type', 'platform', 'architecture', 'downloadSize', 'installedSize', 'modules']
} as const;

export const UnityReleaseSchema = {
    description: 'A Unity Release.',
    type: 'object',
    properties: {
        version: {
            type: 'string',
            description: 'The version of the Unity Release.',
            example: '2020.3.44f1'
        },
        releaseDate: {
            type: 'string',
            description: 'The release date of the Unity Release.',
            example: '2023-01-18T17:25:53.109Z'
        },
        releaseNotes: {
            '$ref': '#/components/schemas/UnityReleaseNotes',
            description: 'The release notes of the Unity Release.'
        },
        stream: {
            type: 'string',
            enum: ['LTS', 'BETA', 'ALPHA', 'TECH'],
            description: 'The release stream of the Unity Release.',
            nullable: false,
            example: 'LTS'
        },
        downloads: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityReleaseDownload'
            },
            nullable: false,
            description: 'The downloads of the Unity Release.'
        },
        skuFamily: {
            type: 'string',
            enum: ['DOTS', 'CLASSIC'],
            description: 'The SKU family of the Unity Release.',
            nullable: false,
            example: 'CLASSIC'
        },
        recommended: {
            type: 'boolean',
            description: 'The indicator for whether the Unity Release is the recommended LTS version.',
            example: false
        },
        unityHubDeepLink: {
            type: 'string',
            description: 'The Unity Hub deep link of the Unity Release.',
            example: 'unityhub://2020.3.44f1/7f159b6136da'
        },
        shortRevision: {
            type: 'string',
            description: 'The Git Short Revision of the Unity Release.',
            example: '7f159b6136da'
        },
        thirdPartyNotices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityReleaseThirdPartyNotice'
            },
            nullable: false,
            description: 'The Third Party Notices of the Unity Release.',
            example: []
        }
    },
    required: ['version', 'releaseDate', 'releaseNotes', 'stream', 'downloads', 'skuFamily', 'recommended', 'unityHubDeepLink', 'shortRevision', 'thirdPartyNotices']
} as const;

export const UnityReleaseOffsetConnectionSchema = {
    description: 'A relay style offset paginated Unity Release Connection.',
    type: 'object',
    properties: {
        offset: {
            type: 'integer',
            description: 'The input offset of the Unity Release Offset Connection.',
            example: 0
        },
        limit: {
            type: 'integer',
            description: 'The input limit of the Unity Release Offset Connection.',
            example: 10
        },
        total: {
            type: 'integer',
            description: 'The total count of all available Unity Releases in the Unity Release Offset Connection.',
            example: 1027
        },
        results: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UnityRelease'
            },
            nullable: false,
            description: 'The list of Unity Releases in the Unity Release Offset Connection.'
        }
    },
    required: ['offset', 'limit', 'total', 'results']
} as const;

export const GetUnityReleaseValidationErrorSchema = {
    description: 'The Unity Release Bad Request Error.',
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'The title of the Validation Error.',
            example: 'Bad Request'
        },
        status: {
            type: 'integer',
            description: 'The HTTP status code of the Validation Error.',
            example: 400
        },
        detail: {
            type: 'string',
            description: 'The detail of the Validation Error.',
            example: 'querystring.limit should be integer'
        }
    },
    required: ['title', 'status', 'detail']
} as const;

export const GetUnityReleaseInternalServerErrorSchema = {
    description: 'The Unity Release Internal Server Error.',
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'The title of the Internal Server Error.',
            example: 'Internal Server Error'
        },
        status: {
            type: 'integer',
            description: 'The HTTP status code of the Internal Server Error.',
            example: 500
        },
        detail: {
            type: 'string',
            description: 'The detail of the Internal Server Error.',
            example: 'An unknown error occurred'
        }
    },
    required: ['title', 'status', 'detail']
} as const;

export const GetUnityReleaseServiceUnavailableErrorSchema = {
    description: 'The Unity Release Service Unavailable Error.',
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'The title of the Service Unavailable Error.',
            example: 'Service Unavailable'
        },
        status: {
            type: 'integer',
            description: 'The HTTP status code of the Service Unavailable Error.',
            example: 503
        },
        detail: {
            type: 'string',
            description: 'The detail of the Service Unavailable Error.',
            example: 'Service health ping failed'
        }
    },
    required: ['title', 'status', 'detail']
} as const;