// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUnityReleasesData, GetUnityReleasesErrors, GetUnityReleasesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Release {
    /**
     * Get Unity Releases
     * Get Unity Releases.
     * > **Note:** Any unpublished Unity Release will not appear in the queries.
     *
     * With this request, you can get all the Unity Editor Releases. For retrieving releases, we use offset-based pagination.
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?limit=10&offset=0'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 1025,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * > **Info:** If an internal error occurs, an empty list will be returned.
     * > **Note:** Do you need more examples on how to query for Unity Releases? Check out these examples!
     * ### Order by release date
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?order=RELEASE_DATE_ASC'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 1025,
     * "results": [
     * {
     * "version": "5.0.0f4",
     * "releaseDate": "2015-02-25T15:49:05.835Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by Unity Release stream
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?stream=LTS'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 391,
     * "results": [
     * {
     * "version": "2021.3.15f1",
     * "releaseDate": "2022-12-01T17:20:58.301Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by Unity Release download platform
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?platform=WINDOWS'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 1013,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by Unity Release download architecture
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?architecture=X86_64'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 1013,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by a Unity Release version
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?version=2023.1.0a22'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 1,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by a Unity Release major-minor version
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?version=2023.1'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 20,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     * ### Filter by a Unity Release major version
     *
     * **Make request:**
     *
     * ```bash
     * curl 'https://services.api.unity.com/unity/editor/release/v1/releases?version=2023'
     * ```
     *
     * **Response:**
     *
     * ```jsonc
     * {
     * "offset": 0,
     * "limit": 10,
     * "total": 20,
     * "results": [
     * {
     * "version": "2023.1.0a22",
     * "releaseDate": "2022-12-07T21:25:31.942Z"
     * // ...
     * }
     * // ...
     * ]
     * }
     * ```
     *
     */
    public static getUnityReleases<ThrowOnError extends boolean = false>(options?: Options<GetUnityReleasesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUnityReleasesResponses, GetUnityReleasesErrors, ThrowOnError>({
            url: '/unity/editor/release/v1/releases',
            ...options
        });
    }
}
