// This file is auto-generated by @hey-api/openapi-ts

/**
 * A Unity Release Digital Value as defined on Release Live Platform.
 */
export type UnityReleaseDigitalValue = {
    /**
     * The value of the Unity Release Digital Value.
     */
    value: number;
    /**
     * The unit of the Unity Release Digital Value.
     */
    unit: 'BYTE' | 'KILOBYTE' | 'MEGABYTE' | 'GIGABYTE';
};

/**
 * The unit of the Unity Release Digital Value.
 */
export type unit = 'BYTE' | 'KILOBYTE' | 'MEGABYTE' | 'GIGABYTE';

/**
 * A Unity Release Notes File as defined on Release Live Platform.
 */
export type UnityReleaseNotes = {
    /**
     * The URL of the Unity Release notes.
     */
    url: string;
    /**
     * The Subresource Integrity of the Unity Release notes as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.
     */
    integrity?: string;
    /**
     * The file type of the Unity Release notes.
     */
    type: 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';
};

/**
 * The file type of the Unity Release notes.
 */
export type type = 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';

/**
 * A Unity Release Third Party Notice File as defined on Release Live Platform.
 */
export type UnityReleaseThirdPartyNotice = {
    /**
     * The original file name of the Unity Release Third Party Notice.
     */
    originalFileName: string;
    /**
     * The URL of the Unity Release Third Party Notice.
     */
    url: string;
    /**
     * The Subresource Integrity of the Unity Release Third Party Notice as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.
     */
    integrity?: string;
    /**
     * The file type of the Unity Release Third Party Notice.
     */
    type: 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';
};

/**
 * A Unity Release module end-user license agreement.
 */
export type UnityReleaseModuleEula = {
    /**
     * The URL of the Unity Release module end-user license agreement.
     */
    url: string;
    /**
     * The Subresource Integrity of the Unity Release module end-user license agreement as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.
     */
    integrity?: string;
    /**
     * The file type of the Unity Release module end-user license agreement.
     */
    type: 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';
    /**
     * The label of the Unity Release module end-user license agreement.
     */
    label: string;
    /**
     * The message of the Unity Release module end-user license agreement.
     */
    message: string;
};

/**
 * A Unity Release Module Extracted Path Rename.
 */
export type UnityReleaseModuleExtractedPathRename = {
    /**
     * The location of the module when extracted.
     */
    from: string;
    /**
     * The location the module must be moved to.
     */
    to: string;
};

/**
 * A Unity Release module.
 */
export type UnityReleaseModule = {
    /**
     * The ID of the Unity Release module.
     */
    id: string;
    /**
     * The slug of the Unity Release module. This is unique across all Unity Release Modules.
     */
    slug: string;
    /**
     * The name of the Unity Release module.
     */
    name: string;
    /**
     * The description of the Unity Release module.
     */
    description: string;
    /**
     * The category of the Unity Release module.
     */
    category: 'DOCUMENTATION' | 'PLATFORM' | 'LANGUAGE_PACK' | 'DEV_TOOL' | 'PLUGIN' | 'COMPONENT';
    /**
     * The URL of the Unity Release module.
     */
    url: string;
    /**
     * The Subresource Integrity of the Unity Release module as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.
     */
    integrity?: string;
    /**
     * The file type of the Unity Release module.
     */
    type: 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';
    /**
     * The download size of the Unity Release module.
     */
    downloadSize: UnityReleaseDigitalValue;
    /**
     * The installed size of the Unity Release module.
     */
    installedSize: UnityReleaseDigitalValue;
    /**
     * The optional sub-modules of the Unity Release module. The parent must be downloaded to download a sub-module.
     */
    subModules?: Array<UnityReleaseModule> | null;
    /**
     * The indicator for whether the Unity Release module needs to be downloaded if the parent is downloaded.
     */
    required: boolean;
    /**
     * The indicator for whether the Unity Release module needs to be hidden when displaying modules in a UI.
     */
    hidden: boolean;
    /**
     * The location to move a Unity Release Module when extracted or unzipped.
     */
    extractedPathRename?: UnityReleaseModuleExtractedPathRename;
    /**
     * The indicator for whether the Unity Release module should be pre-selected.
     */
    preSelected: boolean;
    /**
     * The file destination of the Unity Release module.
     */
    destination?: string;
    /**
     * The end-user license agreements of the Unity Release module.
     */
    eula?: Array<UnityReleaseModuleEula> | null;
};

/**
 * The category of the Unity Release module.
 */
export type category = 'DOCUMENTATION' | 'PLATFORM' | 'LANGUAGE_PACK' | 'DEV_TOOL' | 'PLUGIN' | 'COMPONENT';

/**
 * A Unity Release Hub download.
 */
export type UnityReleaseDownload = {
    /**
     * The URL of the Unity Release Hub download.
     */
    url: string;
    /**
     * The Subresource Integrity of the Unity Release Hub download as defined by the [W3C Recommendation Subresource Integrity](https://www.w3.org/TR/SRI/). For example, `sha1-OTVjZTI0ZTk5MDg0YTMyYTBmZTdiNTU1NTMwZGRhYjQ3OWMzYzc1MQo=`.
     */
    integrity?: string;
    /**
     * The file type of the Unity Release Hub download.
     */
    type: 'TEXT' | 'TAR_GZ' | 'TAR_XZ' | 'ZIP' | 'PKG' | 'EXE' | 'PO' | 'DMG' | 'LZMA' | 'LZ4' | 'MD' | 'PDF';
    /**
     * The platform of the Unity Release Hub download.
     */
    platform: 'MAC_OS' | 'LINUX' | 'WINDOWS';
    /**
     * The architecture of the Unity Release Hub download.
     */
    architecture: 'X86_64' | 'ARM64';
    /**
     * The download size of the Unity Release Hub download.
     */
    downloadSize: UnityReleaseDigitalValue;
    /**
     * The installed size of the Unity Release Hub download.
     */
    installedSize: UnityReleaseDigitalValue;
    /**
     * The modules of the Unity Release Hub download.
     */
    modules: Array<UnityReleaseModule>;
};

/**
 * The platform of the Unity Release Hub download.
 */
export type platform = 'MAC_OS' | 'LINUX' | 'WINDOWS';

/**
 * The architecture of the Unity Release Hub download.
 */
export type architecture = 'X86_64' | 'ARM64';

/**
 * A Unity Release.
 */
export type UnityRelease = {
    /**
     * The version of the Unity Release.
     */
    version: string;
    /**
     * The release date of the Unity Release.
     */
    releaseDate: string;
    /**
     * The release notes of the Unity Release.
     */
    releaseNotes: UnityReleaseNotes;
    /**
     * The release stream of the Unity Release.
     */
    stream: 'LTS' | 'BETA' | 'ALPHA' | 'TECH';
    /**
     * The downloads of the Unity Release.
     */
    downloads: Array<UnityReleaseDownload>;
    /**
     * The SKU family of the Unity Release.
     */
    skuFamily: 'DOTS' | 'CLASSIC';
    /**
     * The indicator for whether the Unity Release is the recommended LTS version.
     */
    recommended: boolean;
    /**
     * The Unity Hub deep link of the Unity Release.
     */
    unityHubDeepLink: string;
    /**
     * The Git Short Revision of the Unity Release.
     */
    shortRevision: string;
    /**
     * The Third Party Notices of the Unity Release.
     */
    thirdPartyNotices: Array<UnityReleaseThirdPartyNotice>;
};

/**
 * The release stream of the Unity Release.
 */
export type stream = 'LTS' | 'BETA' | 'ALPHA' | 'TECH';

/**
 * The SKU family of the Unity Release.
 */
export type skuFamily = 'DOTS' | 'CLASSIC';

/**
 * A relay style offset paginated Unity Release Connection.
 */
export type UnityReleaseOffsetConnection = {
    /**
     * The input offset of the Unity Release Offset Connection.
     */
    offset: number;
    /**
     * The input limit of the Unity Release Offset Connection.
     */
    limit: number;
    /**
     * The total count of all available Unity Releases in the Unity Release Offset Connection.
     */
    total: number;
    /**
     * The list of Unity Releases in the Unity Release Offset Connection.
     */
    results: Array<UnityRelease>;
};

/**
 * The Unity Release Bad Request Error.
 */
export type GetUnityReleaseValidationError = {
    /**
     * The title of the Validation Error.
     */
    title: string;
    /**
     * The HTTP status code of the Validation Error.
     */
    status: number;
    /**
     * The detail of the Validation Error.
     */
    detail: string;
};

/**
 * The Unity Release Internal Server Error.
 */
export type GetUnityReleaseInternalServerError = {
    /**
     * The title of the Internal Server Error.
     */
    title: string;
    /**
     * The HTTP status code of the Internal Server Error.
     */
    status: number;
    /**
     * The detail of the Internal Server Error.
     */
    detail: string;
};

/**
 * The Unity Release Service Unavailable Error.
 */
export type GetUnityReleaseServiceUnavailableError = {
    /**
     * The title of the Service Unavailable Error.
     */
    title: string;
    /**
     * The HTTP status code of the Service Unavailable Error.
     */
    status: number;
    /**
     * The detail of the Service Unavailable Error.
     */
    detail: string;
};

export type GetUnityReleasesData = {
    query?: {
        /**
         * Filters by Unity Release download architecture.
         */
        architecture?: Array<('X86_64' | 'ARM64')> | null;
        /**
         * Limits the number of results returned per page (min 1, max 25).
         */
        limit?: number;
        /**
         * Offsets the first n elements from the results.
         */
        offset?: number;
        /**
         * Orders the returned results by Get Unity Releases Order.
         */
        order?: ('RELEASE_DATE_ASC' | 'RELEASE_DATE_DESC') | null;
        /**
         * Filters by Unity Release download platform.
         */
        platform?: Array<('MAC_OS' | 'LINUX' | 'WINDOWS')> | null;
        /**
         * Filters by Unity Release stream.
         */
        stream?: Array<('LTS' | 'BETA' | 'ALPHA' | 'TECH')> | null;
        /**
         * Filters by a full text search on the version string.
         */
        version?: string;
    };
};

export type GetUnityReleasesResponse = (UnityReleaseOffsetConnection);

export type GetUnityReleasesError = (GetUnityReleaseValidationError | GetUnityReleaseInternalServerError | GetUnityReleaseServiceUnavailableError);